---
# tasks file for glusterfs-client

- name: Install GlusterFS Fuse Client.
  yum: name={{ item }} state=present
  with_items:
    - glusterfs-fuse
  when: not glusterfs_baserepo_disabled

- name: Install GlusterFS Fuse Client with disable base repo.
  yum: name={{ item }} state=present disablerepo=base
  with_items:
    - glusterfs-fuse
  when: glusterfs_baserepo_disabled
